-- List all Employees whose salary is between 1,000 AND 2,000.
-- Show the Employee Name, Department and Salary.

USE COMPANY1;

SELECT ENAME, DEPTNO, SAL
FROM EMP
WHERE SAL BETWEEN 1000 AND 2000;

USE COMPANY1;

SELECT EMP.ENAME, DEPT.DNAME, EMP.SAL
FROM EMP
INNER JOIN DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO
AND EMP.SAL BETWEEN 1000 AND 2000;